export const translater = {
    // BIO3
    "bio3_fr": "Français",
    "bio3_eng": "Anglais",
    "biostatistique": "Biostatistique",
    "pharmacologie": "Pharmacologie",
    "biotechnologie_env": "Biotechnologie environnementale",
    "biotechnologie_molecuaires": "Biotechnologie moléculaire",
    "genie_genetique": "Génie génétique",
    "genie_enzymatique": "Génie enzymatique",
    "immunologie_technologie_immunologique": "Immunologie technologie Immunologique",
    "genie_biocatalyse": "Génie biocatalyse",
    "technologie_microbienne": "Technologie microbienne",
    "bio3_arabe": "Arabe",
    "bio3_marketing": "Marketing",
    "biosecurite": "Biosécurité et bioéthique",
    "resistance_materiaux": "Résistance materiaux",

    // CH3
    "ch3_fr": "Français",
    "ch3_eng": "Anglais",
    "stategie_sythese": "Stratégie synthèse",
    "gestion_traitement": "Gestion traitement déchets",
    "electrochimie": "Electrochimie",
    "methodes_separation": "Méthodes séparation",
    "automatisation_regulation_capteurs_trait_inf": "Automatisation régulation capteurs traitement informatique",
    "methodes_numeriques": "Méthodes numériques",
    "etas_de_la_matiere": "Etats de la matière",
    "ch3_arabe": "Arabe",
    "ch3_marketing": "Marketing",
    "optimisation": "Optimisation",
    "traitement_des_eaux": "Traitement des eaux",

    // GL3
    "algo": "Algorithmique",
    "num_anal": "Analyse numérique",
    "data_anal": "Analyse des données",
    "optim": "Optimisation",
    "prolog": "Programmation logique",
    "db": "Base de données non relationelles",
    "dist_sys": "Fondement des systèmes répartis",
    "gl3_fr": "Français",
    "gl3_eng": "Anglais",
    "marketing": "Marketing",
    "co_design": "Co-Design",
    "complex": "Complexité des algorithmes",
    "web": "Protocoles de communication web",
    "concept": "Méthodologies de conception",
    "gl3_ppp": "Project personnel professionel",

    // GL4
    "devops": "Devops",
    "traitement_images": "Traitement d'images",
    "grh": "Gestion des ressources humaines",
    "deep_learning": "Deep learning",
    "ihm": "Interface homme-machine",
    "compilation": "Compilation",
    "management_projet": "Management de projet",
    "test_logiciel": "Test logiciel",
    "big_data": "Big data",
    "gl4_eng": "Anglais",
    "architectures_logiciel": "Architectures logicielles",
    "protocoles_de_securite": "Protocoles de sécurité",

    // IIA3
    "ro": "Recherche opérationnelle",
    "auto_indus": "Automatismes industriels",
    "concept_meca": "Conception des systèmes mécaniques",
    "cpp": "Programmation C/C++",
    "iia3_eng": "Anglais",
    "bdd": "Base de données",
    "iia_marketing": "Marketing",
    "management_qualite": "Management de qualité et performance industrielle",
    "tech_acqu_comm": "Technologie d'acquisition de commande d'interfacade",
    "reg_indus": "Régulation industrielle",
    "iia3_fr": "Français",
    "arch_av_proc": "Architecture avancée des processus",
    "mod_id_est": "Modélisation, identification et estimation",

    // IIA4
    "iia4_man_proj": "Management projet",
    "comm_opti": "Commande optimale",
    "imag_embar": "Imagerie embarquée",
    "syst_non_lin": "Systèmes non linéaires",
    "mod_anal_eval": "Modélisation, analyse et évaluation performances",
    "iia4_eng": "Anglais",
    "concept_ordi": "Conception assistée par ordinateur",
    "rli": "R.L.I.",
    "iia4_grh": "Gestion des ressources humaines",
    "arch_prog_sys": "Arch. Prog. Sys.",
    "mach_learn": "Machine Learning",
    "data_sc": "Data Science",
    "inter_liot": "Inter L.I.O.T.",
    "mape": "M.A.P.E",

    // IMI3
    "gmao": "G.M.A.O.",
    "thermo_app": "Thermodynamiques appliquées",
    "instru_opti": "Instrumentation optiques",
    "maintenance": "Tableau de bord de maintenance",
    "meca_fluide": "Mécanique des fluides et thermique",
    "resaux_info": "Réseaux informatiques",
    "thermo_indus": "Thermodynamique industrielle",
    "gpao": "G.P.A.O.",
    "dsp": "Micro contrôleurs DSP",
    "trait_sign": "Traitement de numérique du signal",
    "imi3_eng": "Anglais",
    "arab": "Arabe",
    "imi3_fr": "Français",
    "market": "Marketing",

    // IMI4
    "imi4_grh": "Gestion des ressources humaines",
    "cem": "CEM sécurité des installations",
    "meca_continus_solides": "Mécanique des milieux continus solides",
    "sc_mat": "Science des matériaux",
    "cfao": "C.F.A.O.",
    "comm_machi": "Commande des machines",
    "imi4_man_proj": "Management projet",
    "info_instrum": "Informatique pour l'instrumentation",
    "imi4_eng": "Anglais",
    "capt_int_com": "Capteurs int. com.",
    "micro_electro": "Micro électronique",
    "intell_art": "Intelligence artificielle",
    "temps_reel": "Temps réel",
    "aerodynamique": "Aérodynamique",

    // MPI
    "anal": "Analyse",
    "sl": "Systèmes logiques",
    "magneto": "Electromagnétisme",
    "thermo": "Thermodynamique",
    "electro": "Electronique",
    "info": "Algorithmique et structures de données",
    "alge": "Algébre",
    "mpi_fr": "Français",
    "eco": "Economie",
    "mpi_eng": "Anglais",
    "prog": "Programmation II",

    // CBA
    "cba_eng": "Anglais",
    "atom_mol": "Atome molecule",
    "chim_org": "Chimie organique",
    "stats": "Statistique",
    "react_nsp": "Reactivité NSP",
    "bioch_struct": "Biochimie structurale",
    "physi": "Physique",
    "phys_flui": "Physique fluides",
    "cba_fr": "Français",
    "infor": "Informatique",

    // RT3
    "rt3_fr": "Français",
    "stochastiques": "Processus stochastiques",
    "securite_res": "Sécurité des réseaux",
    "inge_proto": "Ingénierie protocoles",
    "rt3_ppp": "Project personnel professionel",
    "rt3_marketing": "Marketing",
    "res_radio": "Réseaux radiomobiles",
    "logique": "Logique",
    "jee": "Développement javaEE",
    "rt3_eng": "Anglais",
    "rt3_data_anal": "Analyse des données",
    "admin_serv": "Administration et surveillance des réseaux",
    "anal_num": "Analyse numérique",
    "sign_sys": "Signaux systèmes",
    "admin_bd": "Administration de bases de données",

    // RT4
    "theor_lang": "Théorie des langues",
    "fond_syst_rep": "Fondement des systèmes répartis",
    "theor_info": "Théorie de l'information",
    "rt4_eng": "Anglais",
    "cloud_vis": "Cloud et virtualisation",
    "traite_img": "Traitement d'images",
    "deep_learni": "DEEP learning",
    "business_intel": "Business intelligence",
    "rt4_grh": "Gestion des ressources humaines",
    "eval_perf": "Evaluation des performances",
    "rt4_man_proj": "Management projet",
    "big_dat": "Big data",
    "real_virt": "Réalité virtuelle",
    "crypto": "Cryptographie",
};