export const translater = {
    // GL3
    "algo": "Algorithmique",
    "num_anal": "Analyse numérique",
    "data_anal": "Analyse des données",
    "optim": "Optimisation",
    "prolog": "Programmation logique",
    "db": "Base de données non relationelles",
    "dist_sys": "Fondement des systèmes répartis",
    "gl3_fr": "Français",
    "gl3_eng": "Anglais",
    "marketing": "Marketing",
    "co_design": "Co-Design",
    "complex": "Complexité des algorithmes",
    "web": "Protocoles de communication web",
    "concept": "Méthodologies de conception",
    "gl3_ppp": "Project personnel professionel",

    // GL4
    "devops": "Devops",
    "traitement_images": "Traitement d'images",
    "grh": "Gestion des ressources humaines",
    "deep_learning": "Deep learning",
    "ihm": "Interface homme-machine",
    "compilation": "Compilation",
    "management_projet": "Management de projet",
    "test_logiciel": "Test logiciel",
    "big_data": "Big data",
    "gl4_eng": "Anglais",
    "architectures_logiciel": "Architectures logicielles",
    "protocoles_de_securite": "Protocoles de sécurité",

    // IIA3
    "ro": "Recherche opérationnelle",
    "auto_indus": "Automatismes industriels",
    "concept_meca": "Conception des systèmes mécaniques",
    "cpp": "Programmation C/C++",
    "iia3_eng": "Anglais",
    "bdd": "Base de données",
    "iia_marketing": "Marketing",
    "management_qualite": "Management de qualité et performance industrielle",
    "tech_acqu_comm": "Technologie d'acquisition de commande d'interfacade",
    "reg_indus": "Régulation industrielle",
    "iia3_fr": "Français",
    "arch_av_proc": "Architecture avancée des processus",
    "mod_id_est": "Modélisation, identification et estimation",

    // IMI3
    "gmao": "G.M.A.O.",
    "thermo_app": "Thermodynamiques appliquées",
    "instru_opti": "Instrumentation optiques",
    "maintenance": "Tableau de bord de maintenance",
    "meca_fluide": "Mécanique des fluides et thermique",
    "resaux_info": "Réseaux informatiques",
    "thermo_indus": "Thermodynamique industrielle",
    "gpao": "G.P.A.O.",
    "dsp": "Micro contrôleurs DSP",
    "trait_sign": "Traitement de numérique du signal",
    "imi3_eng": "Anglais",
    "arab": "Arabe",
    "imi3_fr": "Français",
    "market": "Marketing",

    // MPI
    "anal": "Analyse",
    "sl": "Systèmes logiques",
    "magneto": "Electromagnétisme",
    "thermo": "Thermodynamique",
    "electro": "Electronique",
    "info": "Algorithmique et structures de données",
    "alge": "Algébre",
    "mpi_fr": "Français",
    "eco": "Economie",
    "mpi_eng": "Anglais",
    "prog": "Programmation II",

    // RT3
    "rt3_fr": "Français",
    "stochastiques": "Processus stochastiques",
    "securite_res": "Sécurité des réseaux",
    "inge_proto": "Ingénierie protocoles",
    "rt3_ppp": "Project personnel professionel",
    "rt3_marketing": "Marketing",
    "res_radio": "Réseaux radiomobiles",
    "logique": "Logique",
    "jee": "Développement javaEE",
    "rt3_eng": "Anglais",
    "rt3_data_anal": "Analyse des données",
    "admin_serv": "Administration et surveillance des réseaux",
    "anal_num": "Analyse numérique",
    "sign_sys": "Signaux systèmes",
    "admin_bd": "Administration de bases de données",
};